<?php
// AT MINIMUM UNCOMMENT AND CONFIGURE ONE OF THE FOLLOWING OPTIONS:

// OPTION ONE: READ MYSQL CONFIG FROM config.lua - RECOMMENDED
define('TFS_CONFIG', '/home/vagrant/forgottenserver/config.lua');

// OPTION TWO: SPECIFY MYSQL CONNECTION DETAILS HERE
// define('TFS_CONFIG', array('mysqlHost' => '127.0.0.1', 'mysqlDatabase' => 'tfs', 'mysqlUser' => 'tfs', 'mysqlPass' => 'tfs'));
// THIS OPTION IS DISCOURAGED AS SOME CODE MIGHT DEPEND ON OTHER VALUES FROM TFS CONFIG

// IF YOU WANT TO CHANGE SOMETHING ELSE, BE SMART AND FOLLOW THE PATTERN
define('CORS_ALLOW_ORIGIN', '*');
define('ENABLE_DEBUG', true);
